#!/bin/sh
set -e

if ! command -v asdf >/dev/null
then
  echo "Install asdf first!" >&2
  exit 1
fi

mkdir -p ~/.asdf

for d in bin lib libexec; do
  ln -sv /usr/local/opt/asdf/$d ~/.asdf/$d
done

asdf plugin-add clojure https://github.com/vic/asdf-clojure
asdf plugin-add elm https://github.com/vic/asdf-elm
asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir
asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang
asdf plugin-add go https://github.com/kennyp/asdf-golang
asdf plugin-add idris https://github.com/vic/asdf-idris
asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs
asdf plugin-add python https://github.com/tuvistavie/asdf-python
asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby

export GNUPGHOME="${ASDF_DIR:-$HOME/.asdf}/keyrings/nodejs" && \
	mkdir -p "$GNUPGHOME" && \
	chmod 0700 "$GNUPGHOME"

"$ASDF_DIR"/plugins/nodejs/bin/import-release-team-keyring

asdf install clojure 1.9.0
asdf install elm 0.19.1
asdf install elixir 1.10.3
asdf install erlang 23.0
asdf install go 1.14.3
asdf install nodejs 14.2.0
asdf install python 3.8.3
asdf install ruby 2.7.1
asdf install ruby jruby-9.2.11.1
