#!/bin/sh
# Run by Strap after installing Brewfile dependencies

cd $(dirname $0)/..

script/install-asdf-plugins
script/install-vscode-extensions

env PERL5LIB=~/perl5/lib/perl5 cpanm --local-lib ~/perl5 JSON JSON::XS YAML local::lib
