#!/bin/sh
# Run by Strap after installing Brewfile dependencies

cd $(dirname $0)/..

# Configure TouchID for sudo
# See: https://support.apple.com/en-gb/109030#:~:text=Touch%20ID%20can,across%20software%20updates
if [ ! -f /etc/pam.d/sudo_local ]; then
  sed -E 's/^#(auth)/\1/' /etc/pam.d/sudo_local.template > /etc/pam.d/sudo_local
fi

script/install-asdf-plugins
script/install-vscode-extensions

env PERL5LIB=~/perl5/lib/perl5 cpanm --local-lib ~/perl5 JSON JSON::XS YAML local::lib

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
